### ISSUE TITLE
 Check parameters when grouping in multiple columns

### ISSUE THREAD

**Issue by beobest2** [databricks/koalas#1252]
```python
>>> pdf = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
...                     'foo', 'bar', 'foo', 'foo'],
...                     'B': ['one', 'one', 'two', 'three',
...                     'two', 'two', 'one', 'three'],
...                     'C': np.random.randn(8),
...                     'D': np.random.randn(8)})
>>> kdf = ks.from_pandas(pdf)
```

Checking grouping by multiple columns forms a hierarchical index. I works fine.
```python
>>> kdf.groupby(['B', 'A']).sum().sort_index()
                  C         D
B     A
one   bar -0.193929  0.193662
      foo  1.134526 -0.062965
three bar  1.075517 -0.621216
      foo  1.297346 -0.462547
two   bar  0.509226  1.057209
      foo  0.911734  0.284388
>>> pdf.groupby(['B', 'A']).sum()
                  C         D
B     A
one   bar -0.193929  0.193662
      foo  1.134526 -0.062965
three bar  1.075517 -0.621216
      foo  1.297346 -0.462547
two   bar  0.509226  1.057209
      foo  0.911734  0.284388
```

I missed square brackets around the parameter to __groupby__.
koalas couldn't catch a mistake and did __groupby__ job with the first parameter ('B' column).

```python
>>> kdf.groupby('B', 'A').sum().sort_index()
              C         D
B
one    0.940597  0.130697
three  2.372863 -1.083763
two    1.420961  1.341598
>>> pdf.groupby('B', 'A').sum()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 7883, in groupby
    axis = self._get_axis_number(axis)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 411, in _get_axis_number
    raise ValueError("No axis named {0} for object type {1}".format(axis, cls))
ValueError: No axis named A for object type <class 'pandas.core.frame.DataFrame'>
>>>
```

**Comment by itholic** [comment]
Thanks for the report.

are you interested in trying to create a Pull Request to fix this?

**Comment by beobest2** [comment]
@itholic You're welcome :) I'm going to take a look at this

**Comment by beobest2** [comment]
I submitted PR https://github.com/databricks/koalas/pull/1253
