### ISSUE TITLE
ValueError when creating koalas Dataframe with duplicate column name

### ISSUE THREAD

**Issue by beobest2** [databricks/koalas#1255]
There is ValueError when creating koalas Dataframe with duplicate column name.
```python
>>> pdf = pd.DataFrame(np.random.randn(5, 5),
...                   columns=['a', 'c', 'b', 'b', 'a'],
...                   index=['Joe', 'Joe', 'Travis', 'Travis', 'Travis'])
>>> pdf
               a         c         b         b         a
Joe    -0.865145 -0.006487 -1.410585  0.996534  0.369394
Joe    -1.017601  0.808152 -0.412281 -0.004824 -0.419562
Travis -0.405356  0.540787 -0.863082  0.891709  1.839520
Travis -1.415441 -1.337224 -0.785092 -1.018160  1.336162
Travis -2.050251  1.389728  0.036075 -1.583323 -3.696555
>>> kdf = ks.from_pandas(pdf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hw/Desktop/dev/git_koalas/koalas/databricks/koalas/namespace.py", line 70, in from_pandas
    return DataFrame(pobj)
  File "/Users/hw/Desktop/dev/git_koalas/koalas/databricks/koalas/frame.py", line 380, in __init__
    super(DataFrame, self).__init__(_InternalFrame.from_pandas(pdf))
  File "/Users/hw/Desktop/dev/git_koalas/koalas/databricks/koalas/internal.py", line 921, in from_pandas
    sdf = default_session().createDataFrame(reset_index, schema=schema)
  File "/usr/local/lib/python3.7/site-packages/pyspark/sql/session.py", line 724, in createDataFrame
    data = self._convert_from_pandas(data, schema, timezone)
  File "/usr/local/lib/python3.7/site-packages/pyspark/sql/session.py", line 487, in _convert_from_pandas
    np_records = pdf.to_records(index=False)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 1824, in to_records
    return np.rec.fromarrays(arrays, dtype={"names": names, "formats": formats})
  File "/usr/local/lib/python3.7/site-packages/numpy/core/records.py", line 618, in fromarrays
    descr = sb.dtype(dtype)
ValueError: name already used as a name or title
```

It works fine without duplicate column name.
```python
>>> pdf = pd.DataFrame(np.random.randn(5, 5),
...                   columns=['a', 'c', 'b', 'b1', 'a1'],
...                   index=['Joe', 'Joe', 'Travis', 'Travis', 'Travis'])
>>> pdf
               a         c         b        b1        a1
Joe     0.753069 -1.014067  0.154648 -0.731109 -0.302279
Joe    -1.678150 -0.252196  0.939639 -0.907443  0.440821
Travis  0.432489 -0.962521  0.486859 -1.701143 -0.017991
Travis  0.650316 -1.125226 -0.403401 -0.349617  0.983986
Travis  0.637044 -0.412164  1.424705 -0.459249  3.323804
>>> kdf = ks.from_pandas(pdf)
>>> kdf
               a         c         b        b1        a1
Joe     0.753069 -1.014067  0.154648 -0.731109 -0.302279
Joe    -1.678150 -0.252196  0.939639 -0.907443  0.440821
Travis  0.432489 -0.962521  0.486859 -1.701143 -0.017991
Travis  0.650316 -1.125226 -0.403401 -0.349617  0.983986
Travis  0.637044 -0.412164  1.424705 -0.459249  3.323804

```

**Comment by HyukjinKwon** [comment]
This limitation is actually inherited from Spark. I don't think there's a good way to handle this. It is documented under https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html#do-not-use-duplicated-column-names at this moment.

**Comment by beobest2** [comment]
@HyukjinKwon  I missed the document. Thanks for the explanation :)
