### ISSUE TITLE
How to can I set it up for driver memory for pyspark on Koalas?

### ISSUE THREAD

**Issue by krazyeom** [databricks/koalas#1607]
When I test a sample code on [https://gist.github.com/patryk-oleniuk/043f97ae9c405cbd13b6977e7e6d6fbc](https://gist.github.com/patryk-oleniuk/043f97ae9c405cbd13b6977e7e6d6fbc)

but I've got the following error message after running the code.

```
2020-06-23 10:30:51 WARN  TaskSetManager:66 - Stage 0 contains a task of very large size (73693 KB). The maximum recommended task size is 100 KB.
[Stage 0:>                                                          (0 + 1) / 8]Exception in thread "dispatcher-event-loop-3" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at org.apache.spark.util.ByteBufferOutputStream.write(ByteBufferOutputStream.scala:41)
```

I think it has only 1g memory to run pyspark for driver. I'd like to config it for more than 1g. But I cannot find a config file on Koalas. I tried to set the config file up for *5g* on `spark/conf/spark-defaults.conf`. It still run with *1g* memory.

```
brighti+  4127  3302  1 10:29 ?        00:00:22 /home/brightics/brightics/packages/java/bin/java -cp /home/brightics/brightics/packages/conda/lib/python3.6/site-packages/pyspark/conf:/home/brightics/brightics/packages/conda/lib/python3.6/site-packages/pyspark/jars/* -Xmx1g org.apache.spark.deploy.SparkSubmit --conf spark.sql.analyzer.failAmbiguousSelfJoin=False --conf spark.app.name=Koalas pyspark-shell
```

How can I set it up for a driver memory for pyspark?

**Comment by HyukjinKwon** [comment]
There was a similar issue answered at https://github.com/databricks/koalas/issues/632. See also https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html#leverage-pyspark-apis
