### ISSUE TITLE
StackOverflowError when using  ks.append

### ISSUE THREAD

**Issue by Lukas012** [databricks/koalas#1652]
```python

os.environ["PYSPARK_PYTHON"] = "/opt/conda/envs/spark3/bin/python"
os.environ['PYSPARK_SUBMIT_ARGS'] = "--packages io.delta:delta-core_2.12:0.7.0 pyspark-shell "
spark = SparkSession \
        .builder \
        .master("spark://my_master:7077") \
        .config("spark.executor.memory", "15g") \
        .config("spark.driver.memory", "3g") \
        .config("spark.sql.execution.arrow.enabled", "true") \
        .config("spark.sql.execution.arrow.fallback.enabled", "true") \
        .config("spark.cores.max", "55") \
        .config("spark.executor.cores", "11") \
        .appName("my_app") \
        .getOrCreate()
ks.set_option('compute.default_index_type', 'distributed')

TABLE = "/my/delta/table/" 
kdf = ks.read_delta(TABLE) # 10 million rows, 100 columns, numbers only
kdfbig = ks.read_delta(TABLE) 

for x in range(300):
    kdfbig = kdfbig.append(kdf, ignore_index=True) # Driver CPU usage goes to 100 %.
#kdfbig should now have 3 billion rows

kdfbig.count()
```

While invoking .count() following exception occurs:
```
--------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-9-8f0bba6fd428> in <module>
----> 1 kdfbig.count()

/opt/conda/envs/spark3/lib/python3.8/site-packages/databricks/koalas/frame.py in count(self, axis)
   6172         Name: 0, dtype: int64
   6173         """
-> 6174         return self._reduce_for_stat_function(
   6175             Frame._count_expr, name="count", axis=axis, numeric_only=False
   6176         )

/opt/conda/envs/spark3/lib/python3.8/site-packages/databricks/koalas/frame.py in _reduce_for_stat_function(self, sfun, name, axis, numeric_only)
    635                 )
    636 
--> 637                 return first_series(DataFrame(internal).transpose())
    638 
    639         elif axis == 1:

/opt/conda/envs/spark3/lib/python3.8/site-packages/databricks/koalas/frame.py in transpose(self)
   2080             SPARK_INDEX_NAME_FORMAT(i) for i in range(self._internal.column_labels_level)
   2081         ]
-> 2082         pivoted_df = exploded_df.groupBy(internal_index_columns).pivot("index")
   2083 
   2084         transposed_df = pivoted_df.agg(F.first(F.col("value")))

/opt/conda/envs/spark3/lib/python3.8/site-packages/pyspark/sql/group.py in pivot(self, pivot_col, values)
    215         """
    216         if values is None:
--> 217             jgd = self._jgd.pivot(pivot_col)
    218         else:
    219             jgd = self._jgd.pivot(pivot_col, values)

/opt/conda/envs/spark3/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/opt/conda/envs/spark3/lib/python3.8/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
    129     def deco(*a, **kw):
    130         try:
--> 131             return f(*a, **kw)
    132         except py4j.protocol.Py4JJavaError as e:
    133             converted = convert_exception(e.java_exception)

/opt/conda/envs/spark3/lib/python3.8/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o120307.pivot.
: java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.get(HashMap.java:557)
	at java.util.Collections$SynchronizedMap.get(Collections.java:2584)
	at org.apache.spark.internal.config.MapProvider.get(ConfigProvider.scala:47)
	at org.apache.spark.internal.config.ConfigReader.get(ConfigReader.scala:79)
	at org.apache.spark.internal.config.ConfigEntry.readString(ConfigEntry.scala:65)
	at org.apache.spark.internal.config.ConfigEntryWithDefault.readFrom(ConfigEntry.scala:112)
	at org.apache.spark.sql.internal.SQLConf.getConf(SQLConf.scala:3210)
	at org.apache.spark.sql.internal.SQLConf.maxToStringFields(SQLConf.scala:3143)
	at org.apache.spark.sql.catalyst.expressions.Expression.toString(Expression.scala:276)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.apache.spark.sql.catalyst.expressions.Alias.toString(namedExpressions.scala:193)
	at java.lang.String.valueOf(String.java:2994)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:203)
	at scala.collection.TraversableOnce.$anonfun$addString$1(TraversableOnce.scala:364)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.addString(TraversableOnce.scala:362)
	at scala.collection.TraversableOnce.addString$(TraversableOnce.scala:358)
	at scala.collection.AbstractTraversable.addString(Traversable.scala:108)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:328)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:327)
	at scala.collection.AbstractTraversable.mkString(Traversable.scala:108)
	at org.apache.spark.sql.catalyst.util.package$.truncatedString(package.scala:181)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$argString$1(TreeNode.scala:535)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.TraversableOnce.addString(TraversableOnce.scala:362)
	at scala.collection.TraversableOnce.addString$(TraversableOnce.scala:358)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1429)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:328)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:327)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1429)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:330)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:330)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1429)
	at org.apache.spark.sql.catalyst.trees.TreeNode.argString(TreeNode.scala:549)
	at org.apache.spark.sql.catalyst.trees.TreeNode.simpleString(TreeNode.scala:556)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.simpleString(QueryPlan.scala:188)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.verboseString(QueryPlan.scala:190)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:669)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:697)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:697)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$generateTreeString$3(TreeNode.scala:693)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$generateTreeString$3$adapted(TreeNode.scala:691)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:691)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:697)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:697)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:697)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$generateTreeString$3(TreeNode.scala:693)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$generateTreeString$3$adapted(TreeNode.scala:691)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:691)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:697)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:697)
	at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:697)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$generateTreeString$3(TreeNode.scala:693)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$generateTreeString$3$adapted(TreeNode.scala:691)
	at scala.collection.immutable.List.foreach(List.scala:392)
(......)
```

Why do I get a stackoverflow exception? On my spark worker nodes there is enough Memory. It seems to me, that the driver memory is the limit, but I don't understand why it does not execute the .append on the workers?

**Comment by HyukjinKwon** [comment]
I think this is a typical issue of self-appending multiple times:

```python
for x in range(300):
    kdfbig = kdfbig.append(kdf, ignore_index=True)
```

this kind of pattern doesn't work very well at Spark in general.

**Comment by Lukas012** [comment]
Ok. So I close.
