### ISSUE TITLE
Problem using read_sql

### ISSUE THREAD

**Issue by adelgadof** [databricks/koalas#2099]
Hello!  

First of all sorry if what I'm asking is solved somewhere else, I haven't found any solution to this issue.

Basically, I'm trying to use the read_sql() function the same way I do on pandas and it won't come out correctly. The read_sql() documentation doesn't give me much information either, so I was hoping someone around here would know what to do, or if this is an expected error.

The code would basically be:

```
engine = 'mssql+pyodbc://<User>:<PW>@<IP>?driver=ODBC+Driver+17+for+SQL+Server;currentSchema=<CS>'

ks.read_sql("SELECT * FROM <database>", engine)  

```
The same query on pandas works fine. I have tried some variations on the engine obtaining no results. From the error sequence I understand the the driver is the problem, but really don't know what should I do, since I can use that driver on Pandas. Koalas documentation of read_sql just give two basic examples of postgres, so I'm kinda lost of what can I do.

```
Py4JJavaError: An error occurred while calling o70.load.
: java.sql.SQLException: No suitable driver
	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$2(JDBCOptions.scala:105)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:105)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:35)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:32)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:344)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by itholic** [comment]
Seems like you're using ODBC driver,
but unfortunately Koalas only supports for JDBC connector for now described as below in the [documents](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.read_sql.html).

![Screen Shot 2021-03-15 at 1 34 05 PM](https://user-images.githubusercontent.com/44108233/111104060-23aa9280-8593-11eb-915f-1104f37c8682.png)

**Comment by adelgadof** [comment]
Oh, thank you!
