### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by loungehub** [databricks/koalas#2234]
When I import databricks.koalas as ks, I get error as follows: 
Can you help me how to solve this issue?

>>> import databricks.koalas as ks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/opt/anaconda3/envs/biodiversity/lib/python3.11/site-packages/databricks/koalas/__init__.py", line 49, in <module>
    from databricks.koalas.frame import DataFrame
  File "/Users/opt/anaconda3/envs/biodiversity/lib/python3.11/site-packages/databricks/koalas/frame.py", line 33, in <module>
    from pandas.api.types import is_list_like, is_dict_like
ModuleNotFoundError: No module named 'pandas.api'

**Comment by itholic** [comment]
same as https://github.com/databricks/koalas/issues/2235. Let me close this one as it seems like duplicated
