### ISSUE TITLE
unique function is broken

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#233]
```
df = ks.DataFrame({"Person": ['a', 'b', 'b', 'c']})
df
  Person
0      a
1      b
2      b
3      c

df.unique()
  Person
2      b
3      c
0      a
1      b
```

**Comment by HyukjinKwon** [comment]
Seems like Pandas DataFrame doesn't have `unique`:

```python
>>> import pandas as pd
>>> pd.DataFrame({"Person": ['a', 'b', 'b', 'c']})
  Person
0      a
1      b
2      b
3      c
>>> df = pd.DataFrame({"Person": ['a', 'b', 'b', 'c']})
>>> df.unique()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'unique'
>>> df.Person.unique()
array(['a', 'b', 'c'], dtype=object)
```

but series has it. Let me target to fix Series one.

**Comment by rxin** [comment]
Yea maybe we should remove DataFrame.unique then and only keep Series.unique.
