### ISSUE TITLE
Series.astype does not understand Spark type strings

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#340]
```
>>> import databricks.koalas as ks
>>> ks.range(10)['id'].astype('INT')
  File "<stdin>", line 1, in <module>
  File "/.../databricks/koalas/series.py", line 294, in astype
    raise ValueError("Type {} not understood".format(dtype))
ValueError: Type INT not understood
```

```
>>> ks.range(10)['id'].astype('timestamp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../koalas/databricks/koalas/series.py", line 294, in astype
    raise ValueError("Type {} not understood".format(dtype))
ValueError: Type timestamp not understood
```

**Comment by rxin** [comment]
Related to this, we should also support the Spark type object, e.g. IntegerType.

**Comment by HyukjinKwon** [comment]
I am having a offline discussion with @rxin (and Reynold will be on the vacation for the next week).
I will share the rough summary of the discussion when it's finished.

Since the release will happen in the middle of the next week, I will get rid of the release version for now. But please bring it back @rxin if you think it should be done. I will take a look and get this done first.

**Comment by thunterdb** [comment]
We should centralize all the type conversions in this function, there are a couple of places where they appear:
https://github.com/databricks/koalas/blob/master/databricks/koalas/typedef.py#L129

By the way, if you use that function and the lower case, it should work.

**Comment by HyukjinKwon** [comment]
Ah, yea. Actually PySpark side delegates such type parsing into SQL parser. I was thinking about doing the same thing. but we should consider struct, map types etc. and maybe alowing those might lead to confusions. Like .. users could complain why Koalas dataframe doesn't take PySpark's column as arguments.
