### ISSUE TITLE
Error initializing dataframe on local dev box

### ISSUE THREAD

**Issue by jaymandalal** [databricks/koalas#491]
I have installed Koalas (see install log below) and attempting to play with it and i am encountering some basic issues loading a data frame. Am i missing something? 

--- Repro ---
```
import pandas as pd

import databricks.koalas as ks

d = {'col1': [1, 2], 'col2': [3, 4]}

df = ks.DataFrame(data=d, columns=['col1', 'col2'])
Traceback (most recent call last):

  File "<ipython-input-4-4045c50126d7>", line 1, in <module>
    df = ks.DataFrame(data=d, columns=['col1', 'col2'])

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\databricks\koalas\frame.py", line 257, in __init__
    super(DataFrame, self).__init__(_InternalFrame.from_pandas(pdf))

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\databricks\koalas\internal.py", line 468, in from_pandas
    sdf = default_session().createDataFrame(reset_index, schema=schema)

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\databricks\koalas\utils.py", line 33, in default_session
    return builder.getOrCreate()

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\pyspark\sql\session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\pyspark\context.py", line 367, in getOrCreate
    SparkContext(conf=conf or SparkConf())

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\pyspark\context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\pyspark\context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\pyspark\java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\pyspark\java_gateway.py", line 101, in _launch_gateway
    proc = Popen(command, stdin=PIPE, env=env)

  File "D:\WinPython37\python-3.7.2.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "D:\WinPython37\python-3.7.2.amd64\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)

  File "D:\WinPython37\python-3.7.2.amd64\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

--- Install Log ---
```
E:\> pip install koalas
Collecting koalas
  Downloading https://files.pythonhosted.org/packages/9c/04/f4a111c07926523c903fa130c681b3bbaace3647f5b45f7782a8222a0eda/koalas-0.9.0-py3-none-any.whl (288kB)
     |████████████████████████████████| 296kB 6.8MB/s
Requirement already satisfied: matplotlib>=3.0.0 in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from koalas) (3.0.3)
Requirement already satisfied: pandas>=0.23 in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from koalas) (0.24.1)
Requirement already satisfied: pyarrow>=0.10 in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from koalas) (0.12.1)
Requirement already satisfied: numpy>=1.14 in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from koalas) (1.16.2+mkl)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from matplotlib>=3.0.0->koalas) (1.0.1)
Requirement already satisfied: python-dateutil>=2.1 in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from matplotlib>=3.0.0->koalas) (2.8.0)
Requirement already satisfied: cycler>=0.10 in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from matplotlib>=3.0.0->koalas) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from matplotlib>=3.0.0->koalas) (2.3.1)
Requirement already satisfied: pytz>=2011k in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from pandas>=0.23->koalas) (2018.9)
Requirement already satisfied: six>=1.0.0 in c:\users\jdalal\appdata\roaming\python\python37\site-packages (from pyarrow>=0.10->koalas) (1.12.0)
Requirement already satisfied: setuptools in d:\winpython37\python-3.7.2.amd64\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=3.0.0->koalas) (40.8.0)
Installing collected packages: koalas
Successfully installed koalas-0.9.0
```

**Comment by HyukjinKwon** [comment]
Seems like it's an issue in Spark. Looks Spark was failed to be executed. BTW, Koalas doesn't guarantee Windows support yet as far as I know.

**Comment by HyukjinKwon** [comment]
Can you show what happen when you run a simple example with PySpark?

**Comment by KetaoChen** [comment]
I am using windows 10, and I installed koalas according to the github step by step.
It was stuck at "df = ks.from_pandas(pdf)", and showed System cannot find the path specified.

>>> import databricks.koalas as ks
>>> import pandas as pd
>>> pdf = pd.DataFrame({'x':range(3), 'y':['a','b','b'], 'z':['a','b','b']})
>>> df = ks.from_pandas(pdf)
System cannot find the path specified.


>>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\koalas\databricks\koalas\namespace.py", line 69, in from_pandas
    return DataFrame(pobj)
  File "E:\koalas\databricks\koalas\frame.py", line 374, in __init__
    super(DataFrame, self).__init__(_InternalFrame.from_pandas(pdf))
  File "E:\koalas\databricks\koalas\internal.py", line 738, in from_pandas
    sdf = default_session().createDataFrame(reset_index, schema=schema)
  File "E:\koalas\databricks\koalas\utils.py", line 269, in default_session
    return builder.getOrCreate()
  File "C:\Users\Ketao\AppData\Local\Programs\Python\Python36\lib\site-packages\pyspark\sql\session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "C:\Users\Ketao\AppData\Local\Programs\Python\Python36\lib\site-packages\pyspark\context.py", line 349, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "C:\Users\Ketao\AppData\Local\Programs\Python\Python36\lib\site-packages\pyspark\context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "C:\Users\Ketao\AppData\Local\Programs\Python\Python36\lib\site-packages\pyspark\context.py", line 298, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "C:\Users\Ketao\AppData\Local\Programs\Python\Python36\lib\site-packages\pyspark\java_gateway.py", line 91, in launch_gateway
    time.sleep(0.1)
KeyboardInterrupt

**Comment by HyukjinKwon** [comment]
This one also looks like an issue in PySpark:

```
File "C:\Users\Ketao\AppData\Local\Programs\Python\Python36\lib\site-packages\pyspark\context.py", line 298, in _ensure_initialized
SparkContext._gateway = gateway or launch_gateway(conf)
File "C:\Users\Ketao\AppData\Local\Programs\Python\Python36\lib\site-packages\pyspark\java_gateway.py", line 91, in launch_gateway
```

Are you able to run simple problem written in PySpark?
