### ISSUE TITLE
Getting an indexed column as a Series - doesnt work in pandas

### ISSUE THREAD

**Issue by AbdealiJK** [databricks/koalas#50]
```

In [5]: # Get data
   ...: data = {'a{}'.format(i): [1,2,3,4] for i in range(2)}
   ...: data.update({'b{}'.format(i): ['a', 'b ', ' c', ' d '] for i in range(2)})
   ...: df = pd.DataFrame(data)
   ...: sdf = spark.createDataFrame(df)
   ...:

In [6]: import databricks.koala

In [7]: df = df.set_index('a0')
   ...: sdf = sdf.set_index('a0')
   ...:

In [8]: sdf['a0']

a0
1    1
2    2
3    3
4    4
Name: a0, dtype: int64

In [9]: df['a0']
```

Getting the index as a column seems to work in spark, but fails in pandas.

I guess I'm again coming from the question - What should be expected behavior in koala ?
Is an index considered a column ? (I know internally it is a column ... but i meant from a usability perspective.) Pandas does not think so

**Comment by HyukjinKwon** [comment]
Seems now it's pretty consistent:

```python
>>> import pandas as pd
>>> import databricks.koalas as ks
>>> data = {'a{}'.format(i): [1,2,3,4] for i in range(2)}
>>> data.update({'b{}'.format(i): ['a', 'b ', ' c', ' d '] for i in range(2)})
>>> df = pd.DataFrame(data)
>>> kdf = ks.DataFrame(df)

>>> df = df.set_index('a0')
>>> kdf = kdf.set_index('a0')
```

```
>>> kdf['a0']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hyukjin.kwon/workspace/forked/koalas/databricks/koalas/frame.py", line 6530, in __getitem__
    return self._pd_getitem(key)
  File "/Users/hyukjin.kwon/workspace/forked/koalas/databricks/koalas/frame.py", line 6466, in _pd_getitem
    return self._get_from_multiindex_column((key,))
  File "/Users/hyukjin.kwon/workspace/forked/koalas/databricks/koalas/frame.py", line 6424, in _get_from_multiindex_column
    raise KeyError(k)
KeyError: 'a0'
```

```
>>> df['a0']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'a0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'a0'
```
