### ISSUE TITLE
sort_index is not working with MultiIndex

### ISSUE THREAD

**Issue by garawalid** [databricks/koalas#634]
`DataFrame.sort_index()` is not working when the DataFrame uses MultiIndex.  

Reproduce the error: 
```python
import pandas as pd
import databricks.koalas as ks

pdf = pd.DataFrame({
    ('x', 'a', '1'): [1, 2, 3],
    ('x', 'b', '2'): [4, 5, 6],
    ('y.z', 'c.d', '3'): [7, 8, 9],
    ('x', 'b', '4'): [10, 11, 12],
}, index=[0, 1, 3])

kdf = ks.from_pandas(pdf)

kdf.sort_index()
```

```
Traceback (most recent call last):
  File "/home/xxx/databricks/koalas/tests/bug.py", line 15, in <module>
    kdf.sort_index()
  File "/home/xxx/databricks/koalas/frame.py", line 4295, in sort_index
    inplace=inplace, na_position=na_position)
  File "/home/xxx/databricks/koalas/frame.py", line 4191, in sort_values
    for colname, asc in zip(by, ascending)]
  File "/home/xxx/databricks/koalas/frame.py", line 4191, in <listcomp>
    for colname, asc in zip(by, ascending)]
  File "/home/xxx/databricks/koalas/frame.py", line 6343, in __getitem__
    return self._pd_getitem(key)
  File "/home/xxx/databricks/koalas/frame.py", line 6280, in _pd_getitem
    return self._get_from_multiindex_column((key,))
  File "/home/xxx/databricks/koalas/frame.py", line 6235, in _get_from_multiindex_column
    raise KeyError(k)
KeyError: '__index_level_0__'
```

**Comment by garawalid** [comment]
cc @ueshin

**Comment by ueshin** [comment]
Thanks for the report. I'll work on this.

**Comment by NA-Dev** [comment]
I am sorting a dataframe with multiIndex where one is a string, and one is a date. The sorting is not working properly, as I can see dates are still out of order. Python 3.9 Pandas 1.4.2

![Screenshot 2022-08-16 124124](https://user-images.githubusercontent.com/31260131/184944207-14184056-9eae-46dc-8590-f7a0f8030eaa.png)

**Comment by itholic** [comment]
@NA-Dev Would you mind filing a ticket to [Apache Spark JIRA](https://issues.apache.org/jira/projects/SPARK/issues) ??

Koalas is ported into PySpark as [pandas API on Spark](https://spark.apache.org/docs/latest/api/python/user_guide/pandas_on_spark/index.html).
