### ISSUE TITLE
Series.replace

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#882]
Implement `Series.replace`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.replace.html

**Comment by Patil2099** [comment]
@ueshin Can you explain a little bit about the issue?

**Comment by HyukjinKwon** [comment]
It basically means that we should implement an API that works exactly same as pandas'. For instance see below:

```python
>>> import databricks.koalas as ks
>>> ks.Series([1, 2, 3]).replace()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../koalas/databricks/koalas/missing/__init__.py", line 24, in unsupported_function
    reason=reason)
databricks.koalas.exceptions.PandasNotImplementedError: The method `pd.Series.replace()` is not implemented yet.
```

```python
>>> import pandas as pd
>>> pd.Series([1, 2, 3]).replace()
0    1
1    2
2    3
dtype: int64
```

**Comment by itholic** [comment]
I'm working on this.
