### ISSUE TITLE
BUG: Index setter is not working when `None` is assigned to `name`

### ISSUE THREAD

**Issue by charlesdong1991** [databricks/koalas#971]
with Pandas:
```python
>>> idx = pd.Index([1, 2, 3], name='a')
>>> idx
Int64Index([1, 2, 3], dtype='int64', name='a')
```
if set name to `None` as below:
```python
idx.name = None
```
then idx will turn to 
```python
Int64Index([1, 2, 3], dtype='int64')
```
but in Koalas, this will raise an error, e.g. 
```python
kdf = ks.DataFrame({"a": [1,2,3], index=pd.Index([1, 2, 3], name='a')})
kidx = kdf.index
kidx.name = None
AssertionError
```

**Comment by itholic** [comment]
Good catch 😄 
Are you interested in fix this bug? if not, maybe i can handle it.

**Comment by charlesdong1991** [comment]
haha, you are pretty aggressive on issues!! 😅 
But pls feel free to go fix it if you want! @itholic

**Comment by itholic** [comment]
in my case, it raises `AssertionError` rather than `ValueError` like

```python
>>> kidx.name = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/haejoonlee/Desktop/git_store/koalas/databricks/koalas/indexes.py", line 162, in name
    self.names = [name]
  File "/Users/haejoonlee/Desktop/git_store/koalas/databricks/koalas/indexes.py", line 179, in names
    self._kdf._internal = internal.copy(index_map=list(zip(internal.index_columns, names)))
  File "/Users/haejoonlee/Desktop/git_store/koalas/databricks/koalas/internal.py", line 700, in copy
    column_index=column_index, column_index_names=column_index_names)
  File "/Users/haejoonlee/Desktop/git_store/koalas/databricks/koalas/internal.py", line 420, in __init__
    for index_field, index_name in index_map), index_map
AssertionError: [('a', (None,))]
```

maybe this is an another issue??

**Comment by charlesdong1991** [comment]
ah! sorry about this, this is my bad!

mine is the same, i didn't copy paste the whole error message but simply put a `ValueError` to tell this is not working. I will change it in the issue description.

**Comment by itholic** [comment]
ah i got it !
you don't need to sorry about that since i did made such mistakes here and there 😄 
Anyway, i just made PR about this at #974
